title: LOST
email: 
description: >-
  LOTS - Living Off Security Tools
url: "/Project-Lost"

exclude:
- Gemfile
- Gemfile.lock
- .github

collections:
  tool:
    output: true
    permalink: /:collection/:title

exclude:
- Dockerfile
- Gemfile
- Gemfile.lock
- vendor

highlighter: rouge

defaults:
  - scope:
      path: ''
    values:
      layout: 'default'
  - scope:
      path: ''
      type: 'tool'
    values:
      layout: 'tool'
